AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI GIF Generator - Mock Backend (Node.js)

Resources:
  GenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs18.x
      CodeUri: lambda/
      Events:
        GenerateAPI:
          Type: Api
          Properties:
            Path: /generate
            Method: post
      Policies:
        - AWSLambdaBasicExecutionRole
